version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: docs/environment.yaml

python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt