name: screenpro2
channels:
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - scanpy
  - python-igraph
  - leidenalg
  - pandas<2.0
  - anndata
  - numpy
  - scipy
  - matplotlib<3.7
  - seaborn
  - pyarrow
  - bokeh
  - ipykernel
  - mscorefonts
  - rust>=1.72
  - pip
  - pip:
      - polars
      - biobear
      - numba
      - pydeseq2
      - simple_colors
      - watermark
