name: screenpro2
channels:
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - anndata
  - scanpy
  - python-igraph
  - leidenalg
  - numpy
  - pandas
  - scipy
  - biopython
  - matplotlib
  - seaborn
  - ipykernel
  - mscorefonts
  - pip
  - pip:
      - pydeseq2
      - watermark
