name: screenpro2
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - anndata=0.10.3
  - scanpy=1.9.6
  - python-igraph=0.10.2
  - leidenalg=0.8.8
  - numpy=1.26.0
  - pandas=2.0.3
  - scipy=1.11.3
  - biopython=1.78
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - ipykernel=6.25.0
  - mscorefonts=0.0.1
  - plotnine=0.12.1
  - pip
  - pip:
      - pydeseq2==0.4.1
      - watermark==2.4.3
