name: docs
channels:
  - anaconda
  - conda-forge
dependencies:
  - python
  - myst-parser=0.18.1
  - sphinx=5.3.0
  - sphinx_rtd_theme=1.1.1
  - sphinxcontrib-bibtex
  - pip
  - pip:
      - watermark
