name: docs
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - scanpy
  - python-igraph
  - leidenalg
  - pandas<2.0
  - anndata
  - numpy
  - scipy
  - matplotlib<3.7
  - seaborn
  - bokeh
  - pyarrow
  - ipykernel
  - mscorefonts
  - rust>=1.72
  - myst-parser=0.18.1
  - sphinx=5.3.0
  - sphinx_rtd_theme=1.1.1
  - sphinxcontrib-bibtex
  - pip
  - pip:
      - polars
      - biobear
      - numba
      - pydeseq2
      - simple_colors
      - watermark
