name: docs
channels:
  - anaconda
  - conda-forge
dependencies:
  - python
  - myst-parser
  - sphinx
  - pandas
  - sphinx_rtd_theme
  - anndata
  - scanpy
  - pip
  - pip:
    - nbsphinx
    - pydeseq2
